// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ActivateScene(arg1:string):Promise<domain.AppState>;

export function Bootstrap():Promise<domain.AppState>;

export function ConnectBridge(arg1:string):Promise<domain.AppState>;

export function DataPath():Promise<string>;

export function DeleteDevice(arg1:number):Promise<domain.AppState>;

export function DeleteRule(arg1:number):Promise<domain.AppState>;

export function PingAutomationNow():Promise<string>;

export function RefreshHue():Promise<domain.AppState>;

export function SaveDevice(arg1:domain.Device):Promise<domain.AppState>;

export function SaveRule(arg1:domain.Rule):Promise<domain.AppState>;

export function SetLightBrightness(arg1:string,arg2:number):Promise<domain.AppState>;

export function SetLightColor(arg1:string,arg2:string):Promise<domain.AppState>;

export function SetLightPower(arg1:string,arg2:boolean):Promise<domain.AppState>;
