// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateScene(arg1) {
  return window['go']['backend']['App']['ActivateScene'](arg1);
}

export function Bootstrap() {
  return window['go']['backend']['App']['Bootstrap']();
}

export function ConnectBridge(arg1) {
  return window['go']['backend']['App']['ConnectBridge'](arg1);
}

export function DataPath() {
  return window['go']['backend']['App']['DataPath']();
}

export function DeleteDevice(arg1) {
  return window['go']['backend']['App']['DeleteDevice'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['backend']['App']['DeleteRule'](arg1);
}

export function PingAutomationNow() {
  return window['go']['backend']['App']['PingAutomationNow']();
}

export function RefreshHue() {
  return window['go']['backend']['App']['RefreshHue']();
}

export function SaveDevice(arg1) {
  return window['go']['backend']['App']['SaveDevice'](arg1);
}

export function SaveRule(arg1) {
  return window['go']['backend']['App']['SaveRule'](arg1);
}

export function SetLightBrightness(arg1, arg2) {
  return window['go']['backend']['App']['SetLightBrightness'](arg1, arg2);
}

export function SetLightColor(arg1, arg2) {
  return window['go']['backend']['App']['SetLightColor'](arg1, arg2);
}

export function SetLightPower(arg1, arg2) {
  return window['go']['backend']['App']['SetLightPower'](arg1, arg2);
}
